version: '2'

networks:
  zk-kafka-network:
    driver: bridge

services:
  zoo1:
    image: bitnami/zookeeper:3.6.2
    hostname: zoo1
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_PORT_NUMBER=2181
      - ZOO_SERVERS=zoo1:2888:3888::1
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - zk-kafka-network

  kafka1:
    image: bitnami/kafka:2.6.0
    hostname: kafka1
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    networks:
      - zk-kafka-network 
    depends_on:
      - zoo1